### ISSUE TITLE
Unity 2017.1 compatability

### ISSUE THREAD

**Issue by MikeHergaarden** [WoLfulus/Unity-LineEndingFixer#1]
2017.1 throws an exception:

NullReferenceException: Object reference not set to an instance of an object
WoLfulus.LineEnding.LogEntries.get_consoleFlags () (at Assets/Plugins/Packages/LineEnding/Editor/LogEntries.cs:72)
WoLfulus.LineEnding.FileMonitor.Collect () (at Assets/Plugins/Packages/LineEnding/Editor/FileMonitor.cs:106)

**Comment by WoLfulus** [comment]
I'll take a look at this ASAP.

**Comment by WoLfulus** [comment]
Fixed @ https://github.com/WoLfulus/Unity-LineEndingFixer/commit/8e3b2ea82e1bd92b5e2a6350f0aaf4f90ad145b0
